
module.exports = {
  data:[
        {
            "id": 35763,
            "name": "Cơm Chay Liên Hoa - Đoàn Văn Bơ",
            "tag": "Cơm Chay Liên Hoa - Đoàn Văn Bơ,Cơm Chay Liên Hoa - Đoàn Văn Bơ 004 Chung cư Đoàn Văn Bơ,Cơm Chay Liên Hoa - Đoàn Văn Bơ Quận 4,Cơm Chay Liên Hoa - Đoàn Văn Bơ TP. HCM,Việt Nam 004 Chung cư Đoàn Văn Bơ,Việt Nam Quận 4,Việt Nam TP. HCM,Châu Á 004 Chung cư Đoàn Văn Bơ,Châu Á Quận 4,Châu Á TP. HCM",
            "address": "004 Chung cư Đoàn Văn Bơ",
            "lat": 10.85757,
            "lng": 106.627117,
            "vote": 0,
            "like": 0,
            "alias": "com-chay-lien-hoa-doan-van-bo",
            "avatar": "/upload/img_content/1508494915_avatar_a0TV0VfZ12pbo.jpeg",
            "country": 1,
            "id_category": 1,
            "city": 1,
            "district": 14,
            "last_push": "1990-01-01 00:00:00",
            "end_push": "1990-01-01 00:00:00",
            "line": 339.75456429461,
            "_country": {
                "id": 1,
                "name": "Việt Nam",
                "machine_name": "viet_nam",
                "alias": "viet-nam",
                "zipcode": null,
                "weight": 1
            },
            "_city": {
                "id": 1,
                "name": "Hồ Chí Minh",
                "machine_name": "ho_chi_minh",
                "alias": "ho-chi-minh",
                "id_country": 1,
                "weight": 0
            },
            "_district": {
                "id": 14,
                "name": "Quận 4",
                "machine_name": "quan_4",
                "alias": "quan-4",
                "id_city": 1,
                "weight": 4
            },
            "_category_type": {
                "id": 1,
                "name": "Đồ ăn",
                "machine_name": "food",
                "alias": "do-an",
                "description": null,
                "language": "vn",
                "image": "/upload/category/1507776889.svg",
                "background": "/frontend/assets/img/upload/bg-food2.jpg",
                "weight": 1,
                "parent": 0,
                "active": 1,
                "deleted": 0,
                "created_at": "2017-06-30 01:32:57",
                "updated_at": "2017-10-24 10:48:26",
                "created_by": 1,
                "updated_by": 1,
                "marker": "/upload/category/bg-1508730247.svg"
            }
        },
        {
            "id": 38946,
            "name": "Ẩm Thực 55",
            "tag": "Ẩm Thực 55,Ẩm Thực 55 55 Dương Thị Mười,Ẩm Thực 55 Quận 12,Ẩm Thực 55 TP. HCM,Việt Nam 55 Dương Thị Mười,Việt Nam Quận 12,Việt Nam TP. HCM,Châu Á 55 Dương Thị Mười,Châu Á Quận 12,Châu Á TP. HCM",
            "address": "55 Dương Thị Mười",
            "lat": 10.859243,
            "lng": 106.629865,
            "vote": 0,
            "like": 0,
            "alias": "am-thuc-55",
            "avatar": "/upload/img_content/1511408977_avatar_wcBBlsTgRnIN4.jpeg",
            "country": 1,
            "id_category": 1,
            "city": 1,
            "district": 2,
            "last_push": "1990-01-01 00:00:00",
            "end_push": "1990-01-01 00:00:00",
            "line": 382.69308185211,
            "_country": {
                "id": 1,
                "name": "Việt Nam",
                "machine_name": "viet_nam",
                "alias": "viet-nam",
                "zipcode": null,
                "weight": 1
            },
            "_city": {
                "id": 1,
                "name": "Hồ Chí Minh",
                "machine_name": "ho_chi_minh",
                "alias": "ho-chi-minh",
                "id_country": 1,
                "weight": 0
            },
            "_district": {
                "id": 2,
                "name": "Quận 12",
                "machine_name": "quan_12",
                "alias": "quan-12",
                "id_city": 1,
                "weight": 12
            },
            "_category_type": {
                "id": 1,
                "name": "Đồ ăn",
                "machine_name": "food",
                "alias": "do-an",
                "description": null,
                "language": "vn",
                "image": "/upload/category/1507776889.svg",
                "background": "/frontend/assets/img/upload/bg-food2.jpg",
                "weight": 1,
                "parent": 0,
                "active": 1,
                "deleted": 0,
                "created_at": "2017-06-30 01:32:57",
                "updated_at": "2017-10-24 10:48:26",
                "created_by": 1,
                "updated_by": 1,
                "marker": "/upload/category/bg-1508730247.svg"
            }
        },
        {
            "id": 38963,
            "name": "Bánh Canh Ghẹ Nha Trang 1",
            "tag": "Bánh Canh Ghẹ Nha Trang 1,Bánh Canh Ghẹ Nha Trang 1 50 Tô Ký,Bánh Canh Ghẹ Nha Trang 1 Quận 12,Bánh Canh Ghẹ Nha Trang 1 TP. HCM,Hải sản 50 Tô Ký,Hải sản Quận 12,Hải sản TP. HCM,Việt Nam 50 Tô Ký,Việt Nam Quận 12,Việt Nam TP. HCM,Châu Á 50 Tô Ký,Châu Á Quận 12,Châu Á TP. HCM",
            "address": "50 Tô Ký",
            "lat": 10.854819,
            "lng": 106.624321,
            "vote": 0,
            "like": 0,
            "alias": "banh-canh-ghe-nha-trang-1",
            "avatar": "/upload/img_content/1511409196_avatar_FE5Ek1b8BnhoQ.jpeg",
            "country": 1,
            "id_category": 1,
            "city": 1,
            "district": 2,
            "last_push": "1990-01-01 00:00:00",
            "end_push": "1990-01-01 00:00:00",
            "line": 466.60694379289,
            "_country": {
                "id": 1,
                "name": "Việt Nam",
                "machine_name": "viet_nam",
                "alias": "viet-nam",
                "zipcode": null,
                "weight": 1
            },
            "_city": {
                "id": 1,
                "name": "Hồ Chí Minh",
                "machine_name": "ho_chi_minh",
                "alias": "ho-chi-minh",
                "id_country": 1,
                "weight": 0
            },
            "_district": {
                "id": 2,
                "name": "Quận 12",
                "machine_name": "quan_12",
                "alias": "quan-12",
                "id_city": 1,
                "weight": 12
            },
            "_category_type": {
                "id": 1,
                "name": "Đồ ăn",
                "machine_name": "food",
                "alias": "do-an",
                "description": null,
                "language": "vn",
                "image": "/upload/category/1507776889.svg",
                "background": "/frontend/assets/img/upload/bg-food2.jpg",
                "weight": 1,
                "parent": 0,
                "active": 1,
                "deleted": 0,
                "created_at": "2017-06-30 01:32:57",
                "updated_at": "2017-10-24 10:48:26",
                "created_by": 1,
                "updated_by": 1,
                "marker": "/upload/category/bg-1508730247.svg"
            }
        },
        {
            "id": 38966,
            "name": "Bánh Canh Ghẹ Nha Trang - Tô Ký",
            "tag": "Bánh Canh Ghẹ Nha Trang - Tô Ký,Bánh Canh Ghẹ Nha Trang - Tô Ký 84 Tô Ký,Bánh Canh Ghẹ Nha Trang - Tô Ký Quận 12,Bánh Canh Ghẹ Nha Trang - Tô Ký TP. HCM,Hải sản 84 Tô Ký,Hải sản Quận 12,Hải sản TP. HCM,Việt Nam 84 Tô Ký,Việt Nam Quận 12,Việt Nam TP. HCM,Châu Á 84 Tô Ký,Châu Á Quận 12,Châu Á TP. HCM",
            "address": "84 Tô Ký",
            "lat": 10.8534398,
            "lng": 106.6258256,
            "vote": 0,
            "like": 0,
            "alias": "banh-canh-ghe-nha-trang-to-ky",
            "avatar": "/upload/img_content/1511409218_avatar_dD00LLDuMxoLh.jpeg",
            "country": 1,
            "id_category": 1,
            "city": 1,
            "district": 2,
            "last_push": "1990-01-01 00:00:00",
            "end_push": "1990-01-01 00:00:00",
            "line": 467.68986401821,
            "_country": {
                "id": 1,
                "name": "Việt Nam",
                "machine_name": "viet_nam",
                "alias": "viet-nam",
                "zipcode": null,
                "weight": 1
            },
            "_city": {
                "id": 1,
                "name": "Hồ Chí Minh",
                "machine_name": "ho_chi_minh",
                "alias": "ho-chi-minh",
                "id_country": 1,
                "weight": 0
            },
            "_district": {
                "id": 2,
                "name": "Quận 12",
                "machine_name": "quan_12",
                "alias": "quan-12",
                "id_city": 1,
                "weight": 12
            },
            "_category_type": {
                "id": 1,
                "name": "Đồ ăn",
                "machine_name": "food",
                "alias": "do-an",
                "description": null,
                "language": "vn",
                "image": "/upload/category/1507776889.svg",
                "background": "/frontend/assets/img/upload/bg-food2.jpg",
                "weight": 1,
                "parent": 0,
                "active": 1,
                "deleted": 0,
                "created_at": "2017-06-30 01:32:57",
                "updated_at": "2017-10-24 10:48:26",
                "created_by": 1,
                "updated_by": 1,
                "marker": "/upload/category/bg-1508730247.svg"
            }
        },
        {
            "id": 38944,
            "name": "Quê Ta - Quán Ăn Gia Đình",
            "tag": "Quê Ta - Quán Ăn Gia Đình,Quê Ta - Quán Ăn Gia Đình Hẻm 86 Tân Chánh Hiệp 36,Quê Ta - Quán Ăn Gia Đình Quận 12,Quê Ta - Quán Ăn Gia Đình TP. HCM,Việt Nam Hẻm 86 Tân Chánh Hiệp 36,Việt Nam Quận 12,Việt Nam TP. HCM,Châu Á Hẻm 86 Tân Chánh Hiệp 36,Châu Á Quận 12,Châu Á TP. HCM",
            "address": "Hẻm 86 Tân Chánh Hiệp 36",
            "lat": 10.8580432,
            "lng": 106.6246457,
            "vote": 0,
            "like": 0,
            "alias": "que-ta-quan-an-gia-dinh",
            "avatar": "/upload/img_content/1511408969_avatar_Dkv5uD9UzZX5c.jpeg",
            "country": 1,
            "id_category": 1,
            "city": 1,
            "district": 2,
            "last_push": "1990-01-01 00:00:00",
            "end_push": "1990-01-01 00:00:00",
            "line": 481.08270902808,
            "_country": {
                "id": 1,
                "name": "Việt Nam",
                "machine_name": "viet_nam",
                "alias": "viet-nam",
                "zipcode": null,
                "weight": 1
            },
            "_city": {
                "id": 1,
                "name": "Hồ Chí Minh",
                "machine_name": "ho_chi_minh",
                "alias": "ho-chi-minh",
                "id_country": 1,
                "weight": 0
            },
            "_district": {
                "id": 2,
                "name": "Quận 12",
                "machine_name": "quan_12",
                "alias": "quan-12",
                "id_city": 1,
                "weight": 12
            },
            "_category_type": {
                "id": 1,
                "name": "Đồ ăn",
                "machine_name": "food",
                "alias": "do-an",
                "description": null,
                "language": "vn",
                "image": "/upload/category/1507776889.svg",
                "background": "/frontend/assets/img/upload/bg-food2.jpg",
                "weight": 1,
                "parent": 0,
                "active": 1,
                "deleted": 0,
                "created_at": "2017-06-30 01:32:57",
                "updated_at": "2017-10-24 10:48:26",
                "created_by": 1,
                "updated_by": 1,
                "marker": "/upload/category/bg-1508730247.svg"
            }
        }
    ],
};
